version: '3.8'
services:
  vue:
    build: .
    container_name: vue
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./app:/app
    tty: true
    stdin_open: true
    command: npm run serve